name = "adaptivity"
version = "0.1.0"
defaultTargets = ["AddAdaptivityGap", "MulAdaptivityGap"]

[[lean_lib]]
name = "AddAdaptivityGap"

[[lean_lib]]
name = "MulAdaptivityGap"

[[require]]
name = "mathlib"
scope = "leanprover-community"
